server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
    username: root
    password: "ironfish54#"
    driver-class-name: com.mysql.cj.jdbc.Driver  # ✅ ADDED
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
