server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders_db
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
