server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products_db
    username: root
    password: ironfish54#

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
